### ISSUE TITLE
centos code ready images

### ISSUE THREAD

**Issue by debianmaster** [redhat-developer/codeready-workspaces#103]
are there any centos based images for deployment on okd.

**Comment by debianmaster** [comment]
any luck?

**Comment by debianmaster** [comment]
bump

**Comment by nickboldt** [comment]
If you want to use CentOS-based images, you should look for them in the upstream Che project.

https://github.com/che-dockerfiles/
https://github.com/eclipse/che-devfile-registry/tree/master/arbitrary-users-patch
etc.

For CRW 2, we only support RHEL 8 (UBI 8) based images.

That said we don't support OKD as a deployment target for CRW 2.x. You could try CodeReady Containers instead. 

https://github.com/code-ready/crc/releases

If you'd like to open a new feature request for CRW 2.2, please do so here:

https://issues.redhat.com/browse/CRW
