### ISSUE TITLE
make sure this works on offline installations

### ISSUE THREAD

**Issue by ikke-t** [redhat-developer/codeready-workspaces#129]
CodeReady workspaces must work at customers with no internet connection from OpenShift. That means that any items operator pulls, need to registry url absent. This let's OpenShift search for images from local registry, or any offline mirrored registry user might have.

Also, any url pointing to external resource, like github.com, must be behind ENV variable, so user can clone the required stuff to their internal artifactory/git/etc...

**Comment by nickboldt** [comment]
This is already in place in CodeReady Workspaces 2.0 -- see documents re: restricted environment installation.

https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/2.0/html/installation_guide/installing-codeready-workspaces-in-a-restricted-environment

For 2.1, we'll support OCP 4.4 and 4.3, which improves the way OCP handles offline/airgap. 

See other issues:

* https://issues.redhat.com/browse/CRW-240
* https://issues.redhat.com/browse/CRW-590
* https://github.com/eclipse/che/issues/15350

If you have additional feature requests, please open them in CRW JIRA:

https://issues.redhat.com/browse/CRW
