### ISSUE TITLE
Point to my own Registry for mages

### ISSUE THREAD

**Issue by bortek** [redhat-developer/codeready-workspaces#131]
Guys!

I want to use my own registry instead of redhat's . Right now when I add new workspace codeready created a new deployment in it's namespace called something like this workspacevsygcl4sfri2ka6q.dockerimage

That pod tries to fetch this image from the Internet. 
registry.access.redhat.com/codeready-workspaces/stacks-java

Internet is unavailable but I have my own registry with pullthrough configired which can fetch images. 

Question is how do I  configure codereadyto not to use my own registry address instead of registry.access.redhat.com.

I have tried to change the following without any success.
- Add registry address in Codeready GUI under Aministrtion-Add registry
- Changed this var CHE_INFRA_KUBERNETES_PVC_JOBS_IMAGE and pointed to my registry and this image is now being fetched from my repo but still the above mentioned one is being fetched from edhat

**Comment by RickJWagner** [comment]
Hi Bortek,
This looks like an issue that should be fixed by CRW-172 [1].

This fix should be available with CodeReady 1.1, available soon.  (If this doesn't help, please write back.)

[1] https://issues.jboss.org/browse/CRW-172

**Comment by nickboldt** [comment]
CRW-172 is done.

If you can move to CRW 2.0 or 2.1 (coming next month) then you'll have an even easier time adding your own custom registries.
