### ISSUE TITLE
Plugin registry URL changed (difficult to use Che 7 features in CRW 1.2)

### ISSUE THREAD

**Issue by dmc5179** [redhat-developer/codeready-workspaces#167]
From what I can tell the plugin URI has changed from:

https://che-plugin-registry.openshift.io/plugins
to
https://che-plugin-registry.openshift.io/plugins/v3

When I go into the console to create a workspace; with a python stack for example, and click "Create and Open" the workspace creates just fine. But if instead I select "Create and Proceed editing" I immediately see in the top right corner "Failed to load plugins"

I was attempting to follow this guide:
https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/1.2/html/administration_guide/using-the-che-7-ide-in-codeready-workspaces

And when I create the workspace I get:

Error: Failed to run the workspace: "Error occurred on retrieval of plugin che-machine-exec-plugin:0.0.1. Error: Can't get object by URI 'https://che-plugin-registry.openshift.io/plugins/che-machine-exec-plugin/0.0.1/meta.yaml'. Error: 

The document has moved here. (here being: http://che-plugin-registry.openshift.io/v3/plugins/che-machine-exec-plugin/0.0.1/meta.yaml)

I cannot find where I can configure the registry URI or where I could update it.

**Comment by bryantson** [comment]
I am encountering the same issue.

**Comment by amisevsk** [comment]
Context: during the Che 7 beta (and prior) we went through three iterations on plugin meta yaml structure, and this is where the `/plugins` `/v3/plugins` comes from. 

As a workaround, the way to configure registry URI on a Che server is to set the environment variable `CHE_WORKSPACE_PLUGIN__REGISTRY__URL` on the Che server. For current releases, `https://che-plugin-registry.openshift.io/v3/` should work. 

IIRC the registry is supposed to redirect `/plugins` to `/v3/plugins` so I would need to look further into that though.

**Comment by bryantson** [comment]
@amisevsk Thank you! This worked perfectly well.

**Comment by dmc5179** [comment]
Thank you. I will give that a try as well.

It may not have been clear my my initial report due to how I formatted the error message but the part which says "error the document has moved here" is part of what shows in the Che console. That would lead me to believe that by default, like curl, whatever is being used by Che to pull those plugins does not allow redirects.

**Comment by pwright** [comment]
where should I set CHE_WORKSPACE_PLUGIN__REGISTRY__URL (in an integreatly cluster)?
thx

**Comment by amisevsk** [comment]
@pwright It kind of depends on how Che is set up, but your end goal is to have `CHE_WORKSPACE_PLUGIN__REGISTRY__URL` set as an environment variable in the `che-server` pod. The full docs for configuring Che are [here](https://www.eclipse.org/che/docs/che-7/advanced-configuration-options/), but the short form explanation is
- If Che is deployed via an operator, update the custom resource that the operator created (field is `pluginRegistryUrl`)
- Otherwise, update the `che` configmap to include the value directly.

**Comment by nickboldt** [comment]
I'm going to assume the documented workaround is good enough, since this appears to be a problem restricted to CRW 1.2, which is EOL. 

With 2.x you won't have this problem.
