### ISSUE TITLE
Building codeready container images on s390x arch

### ISSUE THREAD

**Issue by rposts** [redhat-developer/codeready-workspaces#244]
Hi there,

I can't seem to find Dockerfiles/source code for building following images:

- codeready-workspaces/server-operator-rhel8:1.2
- rhscl/postgresql-96-rhel7:1-40
- redhat-sso-7/sso73-openshift:1.0-11
- registry.redhat.io/codeready-workspaces/stacks-java-rhel8:1.2
- registry.redhat.io/codeready-workspaces/stacks-node-rhel8:1.2
- registry.redhat.io/codeready-workspaces/stacks-node:1.2
- registry.redhat.io/codeready-workspaces/stacks-php-rhel8:1.2
- registry.redhat.io/codeready-workspaces/stacks-python-rhel8:1.2
- registry.redhat.io/codeready-workspaces/stacks-dotnet-rhel8:1.2
- registry.redhat.io/codeready-workspaces/stacks-golang-rhel8:1.2
- registry.redhat.io/codeready-workspaces/stacks-java-rhel8:1.2
- registry.redhat.io/codeready-workspaces/stacks-cpp-rhel8:1.2

Can you please point me to appropriate repos and/or instructions on building these images.  I can build codeready-workspaces/server-rhel8:1.2 with no issues but can't find any clues on building others.

Thanks.

**Comment by nickboldt** [comment]
Dockerfiles for the above containers can be found in the RH Container Catalog, eg.,

https://access.redhat.com/containers/?tab=docker-file#/registry.access.redhat.com/codeready-workspaces/server-operator-rhel8/images/1.2

Sources are mostly upstream in Che repos or are forks to apply branding.

For example the operator code is here:

https://github.com/eclipse/che-operator/
which is then transformed via a Jenkins build:
https://github.com/redhat-developer/codeready-workspaces-operator/blob/master/operator.Jenkinsfile
and finally the resulting code is pushed to an internal RH repo from which we can built it offline in Brew.

The stack images should all have Dockerfiles in RHCC, eg.,

https://access.redhat.com/containers/?tab=docker-file#/registry.access.redhat.com/codeready-workspaces/stacks-java-rhel8/images/1.2

To resolve the tarballs referenced in the stack image builds, see:

https://github.com/redhat-developer/codeready-workspaces-deprecated/tree/1.2.2.GA/stacks/dependencies

Note also that CRW 1.2.x is EOL, and we've changed a lot of things in the operator and server for 2.0 and 2.1.

You can find more code here:

* https://github.com/redhat-developer/codeready-workspaces
* https://github.com/redhat-developer/codeready-workspaces-chectl
* https://github.com/redhat-developer/codeready-workspaces-operator
* https://github.com/redhat-developer/codeready-workspaces-theia
* https://github.com/redhat-developer/kubernetes-image-puller

**Comment by nickboldt** [comment]
Should you have any more questions, please ask either for me in the Eclipse Mattermost channel or open a JIRA:

* https://mattermost.eclipse.org/eclipse/channels/eclipse-che
* https://issues.redhat.com/browse/CRW
